server:
  port: 8005


spring:
  application:
    name: gateway

  cloud:    
     gateway:      
       routes:      
            - id: host_route_1        
              uri: https://www.cathaybk.com.tw   
              predicates:        
                - Path=/cath
            - id: host_route_2      
              uri: http://localhost:8081 
              predicates:        
                - Path=/api/hello 
